name: pull-request
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: unional/.github/.github/workflows/yarn-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
